(() => {
  const icons = new Map(window.SEAL_ICON_PROPOSAL.map(item => [item.name, item]))
  const labels = { home:'首页',clock:'最近',star:'星标',share:'分享',send:'发送',cloud:'云空间',users:'我的',pdf:'PDF 工具',mindmap:'思维导图',flow:'流程图',settings:'设置',help:'帮助',search:'搜索',grid:'全部功能',list:'列表',sort:'排序',more:'更多',plus:'新建',retry:'刷新','arrow-left':'返回','doc-word':'文字','doc-table':'表格','doc-ppt':'演示','doc-pdf':'PDF','doc-empty':'文档',bell:'通知',headset:'支持',apps:'应用',ai:'AI 助手',aippt:'演示模板',folder:'文件夹',trash:'回收站',sun:'浅色主题',moon:'深色主题',sliders:'筛选',desktop:'电脑',globe:'在线',tag:'标签',device:'本机','cloud-off':'离线',knowledge:'知识库','download-file':'下载','export-file':'导出',paste:'粘贴',cut:'截屏',copy:'复制','copy-text':'复制文字','copy-all':'复制全文','format-painter':'格式刷',bold:'加粗',italic:'斜体',underline:'下划线',strikethrough:'删除线',subscript:'下标',superscript:'上标','align-left':'左对齐','align-center':'居中','align-right':'右对齐','align-justify':'两端对齐','bullet-list':'项目符号','numbered-list':'编号','indent-increase':'增加缩进','indent-decrease':'减少缩进','line-spacing':'行距',shading:'底纹',undo:'撤销',redo:'重做','find-text':'查找','replace-text':'替换',table:'表格',image:'图片',shape:'形状',symbol:'图标',textbox:'文本框',wordart:'艺术字',chart:'图表',formula:'公式',header:'页眉',footer:'页脚','page-number':'页码',calendar:'日历',link:'链接',bookmark:'书签',crossref:'交叉引用',footnote:'脚注',endnote:'尾注',toc:'目录',caption:'题注',comment:'批注',track:'修订',compare:'比较','spell-check':'拼写检查','word-count':'字数','page-view':'页面','read-view':'阅读','web-view':'网页','outline-view':'大纲','draft-view':'草稿',ruler:'标尺',gridlines:'网格线','paragraph-mark':'段落标记',navigation:'导航','zoom-in':'放大','zoom-out':'缩小','zoom-reset':'重置缩放','fit-width':'适合宽度',watermark:'水印','page-border':'页面边框','page-color':'页面颜色',columns:'分栏','page-break':'分页',margin:'页边距',orientation:'方向','paper-size':'纸张','line-numbers':'行号',open:'导入文件',save:'保存','save-as':'另存为',front:'置于顶层',back:'置于底层',close:'关闭',scan:'图片识别' }
  Object.assign(labels, { 'star-filled':'已星标', member:'会员', wps365:'团队协作', wechat:'微信', language:'语言' })
  const get = (name, platform = active) => icons.get(name)?.[platform] || ''
  const cell = (name, platform = active) => `<div class="icon-cell">${get(name,platform)}<span>${labels[name] || name}</span></div>`
  const files = platform => `<div class="file-samples">${['doc-word','doc-ppt','doc-table','doc-pdf'].map(name => `<div>${get(name,platform)}<span>${labels[name]}</span></div>`).join('')}</div>`
  const ribbon = names => `<div class="ribbon-group"><div class="ribbon-items">${names.map(name=>`<div class="ribbon-button">${get(name,'pc')}<span>${labels[name]}⌄</span></div>`).join('')}</div><small>${names[0] === 'table' ? '表格' : names[0] === 'textbox' ? '文本' : '插图'}</small></div>`
  const fileRows = () => [['doc-word','项目方案与会议纪要','今天 10:24 · 38 KB'],['doc-table','十月项目预算','今天 09:16 · 12 KB'],['doc-ppt','产品功能演示','昨天 16:30 · 1.2 MB'],['doc-pdf','办公资料清单','昨天 14:12 · 286 KB'],['doc-word','团队工作计划','10 月 08 日 · 24 KB']].map(([type,title,detail])=>`<div class="file-row"><div class="file-icon">${get(type,'mobile')}</div><div><div class="file-name">${title}</div><div class="file-detail">${detail}<span class="local">本地</span></div></div><span class="more-icon">${get('more','mobile')}</span></div>`).join('')
  const status = '<div class="phone-status"><span>09:41</span><span>▮▮▮ 5G ▰</span></div>'
  const nav = '<div class="phone-bottom">'+[['home','首页'],['cloud','云空间'],['grid','功能'],['users','我的']].map(([name,label])=>`<div class="nav-item ${name === 'home' ? 'active' : ''}">${get(name,name === 'cloud' ? 'pc' : 'mobile')}<span>${label}</span></div>`).join('')+'</div>'
  const title = (heading,description,sizes) => `<div class="page-title"><div><h1>${heading}</h1><p>${description}</p></div><div class="size-note">${sizes}</div></div>`
  const pc = () => title('PC 端 · 细线条功能区图标','轮廓清楚，少量颜色点缀；以你提供的 WPS 插入工具栏为样式参考。','功能区 20–24 px · 快捷按钮 16 px')+`
  <div class="pc-layout"><div class="desktop"><div class="window-title"><div class="title-left"><img src="assets/seal-office.png" alt="">海豹办公　｜　项目方案.docx</div><span class="window-dots">－ □ ×</span></div><div class="office-tabs"><span>文件</span><span>开始</span><span class="selected">插入</span><span>页面</span><span>引用</span><span>审阅</span><span>视图</span><span>工具</span></div><div class="ribbon">${ribbon(['table'])}${ribbon(['image','doc-empty','cut','shape','symbol'])}${ribbon(['textbox','wordart','chart'])}<div class="ribbon-group"><div class="ribbon-items"><div class="ribbon-button">${get('link','pc')}<span>链接⌄</span></div><div class="ribbon-button">${get('comment','pc')}<span>批注</span></div></div><small>链接与批注</small></div></div><div class="document-work"><div class="page-side"><span>文档导航</span><span>项目概述</span><span>工作安排</span><span>交付说明</span></div><div class="paper"><h3>项目方案</h3><p>统一文档格式，让每一次编辑都清楚、顺手。<br>文字、表格、演示与 PDF，在海豹办公中有一致的使用体验。</p><div class="paper-table"><span>工作事项</span><span>负责人</span><span>进度</span><span>整理项目资料</span><span>项目组</span><span>进行中</span></div></div></div><div class="document-status"><span>第 1 页　共 1 页　｜　字数 128</span><span>150%　－ ━━━━━●━ ＋</span></div></div>
  <aside class="side-board"><h2>尺寸与状态</h2><p>同一个图标，兼顾小尺寸识别。</p><div class="sample-size">${[16,20,24,32].map(size=>`<div class="size-${size}">${get('image','pc')}<span>${size} px</span></div>`).join('')}</div><div class="state-row">${[['normal','默认'],['hover','悬停'],['selected','选中'],['disabled','禁用']].map(([className,label])=>`<div class="state-item ${className}"><div>${get('table','pc')}</div><span>${label}</span></div>`).join('')}</div><div class="group-label">文件类型 · 保留纸张轮廓</div>${files('pc')}</aside></div>
  <section class="board"><div class="board-heading"><h2>主要界面图标</h2><span>文字、表格、演示、PDF 与通用操作</span></div><div class="icon-grid">${['table','image','doc-empty','cut','shape','symbol','textbox','wordart','chart','formula','header','page-number','open','save','paste','copy','format-painter','undo','redo','find-text','link','comment','calendar','settings','home','clock','star','cloud','folder','knowledge','mindmap','flow','grid','export-file','search','help'].map(name=>cell(name,'pc')).join('')}</div></section>`
  const mobile = () => title('移动端 · 彩色分层图标','文件类型用醒目的色块；功能入口用圆润彩色图形，导航保留简洁线条。','文件类型 40–48 px · 功能入口 28–36 px')+`
  <div class="mobile-layout"><section><div class="device-caption">首页 / 最近文件<span>安卓移动端效果</span></div><div class="phone">${status}<div class="phone-header"><img class="avatar" src="assets/seal-office.png" alt="海豹办公"><div class="phone-search">${get('search','mobile')}<span>搜索文件</span></div><span class="small-icon">${get('bell','mobile')}</span></div><div class="phone-content"><div class="phone-hero"><div>${get('scan','mobile')}<span>图片识别</span></div><div>${get('ai','mobile')}<span>AI 助手</span></div></div><div class="quick-strip"><div>${get('open','mobile')}导入文件</div><div>${get('doc-pdf','mobile')}PDF 工具</div><div>${get('aippt','mobile')}演示模板</div></div><div class="file-tabs"><span>本机</span><span class="active">最近</span><span>星标</span><span>文件夹</span></div><div class="list-meta"><span>最近打开</span>${get('sort','mobile')}</div>${fileRows()}</div><div class="floating-plus">${get('plus','mobile')}</div>${nav}</div></section>
  <section><div class="device-caption">新建 / 全部功能<span>同一套图标</span></div><div class="phone sheet-phone">${status}<div class="sheet-underlay">海豹办公　　搜索文件</div><div class="sheet"><div class="sheet-title"><span>新建与功能</span>${get('close','mobile')}</div><div class="sheet-label">Office 文档</div><div class="new-grid">${['doc-word','doc-ppt','doc-table','doc-pdf'].map(name=>`<div class="new-item">${get(name,'mobile')}<span>${labels[name]}</span></div>`).join('')}</div><div class="sheet-label">常用功能</div><div class="new-grid tools">${['open','scan','image','ai','aippt','knowledge','mindmap','flow','cloud','calendar','download-file','settings'].map(name=>`<div class="new-item">${get(name,'mobile')}<span>${labels[name]}</span></div>`).join('')}</div><div class="sheet-rule"></div><div class="sheet-label">编辑工具 · 选中对象后显示</div><div class="mini-nav">${['undo','redo','table','image','textbox','more'].map(name=>get(name,'mobile')).join('')}</div></div></div></section>
  <aside class="mobile-board"><h2>移动端图标总览</h2><p>四种文件一眼区分，分层与折面轻量处理。</p>${files('mobile')}<div class="group-label">彩色功能入口</div><div class="icon-grid">${['scan','open','image','ai','aippt','knowledge','mindmap','flow','cloud','calendar','download-file','copy'].map(name=>cell(name,'mobile')).join('')}</div><div class="group-label">导航 · 默认 / 选中</div><div class="nav-comparison"><div>${get('home','mobile')}<span>首页</span></div><div class="active">${get('home','mobile')}<span>选中</span></div><div>${get('grid','mobile')}<span>功能</span></div><div>${get('users','mobile')}<span>我的</span></div></div></aside></div>`
  let active = new URLSearchParams(location.search).get('view') === 'mobile' ? 'mobile' : 'pc'
  if (new URLSearchParams(location.search).has('capture')) document.body.classList.add('capture')
  const render = () => {
    document.body.dataset.view = active
    document.getElementById('preview').innerHTML = (active === 'pc' ? pc() : mobile()) + `<details class="all-icons"><summary>展开完整图标目录 · ${icons.size} 个</summary><div class="icon-grid">${[...icons.keys()].map(name=>cell(name)).join('')}</div></details>`
    document.querySelectorAll('button[data-view]').forEach(button => button.setAttribute('aria-pressed',String(button.dataset.view === active)))
    document.title = `海豹办公 · ${active === 'pc' ? 'PC' : '移动端'}图标效果稿`
  }
  document.querySelectorAll('button[data-view]').forEach(button => button.addEventListener('click',() => {
    active = button.dataset.view
    const url = new URL(location.href);url.searchParams.set('view',active);history.replaceState(null,'',url)
    render()
  }))
  render()
})()
