server {
  listen 80;
  server_name seal.xingmasoft.com;
  root /www/wwwroot/seal.xingmasoft.com/admin;
  location ^~ /.well-known/acme-challenge/ { root /www/wwwroot/seal.xingmasoft.com; }
  location /api/ {
    proxy_pass http://127.0.0.1:8096/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_read_timeout 40s;
    proxy_send_timeout 40s;
    client_max_body_size 33m;
  }
  location / { try_files $uri $uri/ /index.html; }
  location ~ /\. { deny all; }
  access_log /www/wwwlogs/seal.xingmasoft.com.log;
  error_log /www/wwwlogs/seal.xingmasoft.com.error.log;
}
