const { 创建资源存储 } = require('./resources')

describe('演示资源存储', () => {
  it('复制、删除与撤销分别持有快照引用，关闭历史后才释放字节', () => {
    const 存储 = 创建资源存储()
    const 标识 = 存储.加入(Buffer.from('sample'), 'image/png')
    存储.同步快照('当前', [标识])
    存储.解除引用(标识)
    存储.同步快照('撤销', [标识])
    存储.同步快照('当前', [标识, 标识])
    expect(存储.列表()[0].引用次数).toBe(3)
    存储.同步快照('当前', [])
    存储.清理未引用()
    expect(存储.读取(标识).toString()).toBe('sample')
    存储.同步快照('当前', [标识])
    存储.释放快照('撤销')
    expect(() => 存储.解除引用(标识)).toThrow(/快照/)
    存储.释放快照('当前')
    存储.清理未引用()
    expect(存储.列表()).toEqual([])
  })

  it('导出备份后恢复真实字节，失败恢复和缺失快照均不改变原资源', () => {
    const 原存储 = 创建资源存储()
    const 标识 = 原存储.加入(Buffer.from('sample'), 'image/png')
    const 备份 = 原存储.导出([标识, 标识])
    expect(备份).toHaveLength(1)
    const 存储 = 创建资源存储()
    expect(() => 存储.恢复([...备份, { ...备份[0], 标识: '坏指纹' }])).toThrow(/指纹/)
    expect(存储.列表()).toEqual([])
    存储.恢复(备份)
    存储.同步快照('当前', [标识])
    expect(() => 存储.同步快照('当前', [标识, '缺失'])).toThrow(/不存在/)
    expect(存储.列表()[0].引用次数).toBe(1)
    expect(存储.读取(标识)).toEqual(Buffer.from('sample'))
    expect(() => 存储.恢复([{ ...备份[0], 数据: '!!!!' }])).toThrow(/内容/)
    expect(() => 存储.导出(['缺失'])).toThrow(/不存在/)
  })
  it('相同字节去重，引用解除后仍可供撤销恢复', () => {
    const 存储 = 创建资源存储({ 最大单项字节: 8, 最大总字节: 16 })
    const 首次 = 存储.加入(Buffer.from('sample'), 'image/png')
    const 再次 = 存储.加入(Buffer.from('sample'), 'image/png')
    expect(再次).toBe(首次)
    expect(存储.读取(首次).toString()).toBe('sample')
    存储.解除引用(首次)
    存储.解除引用(首次)
    expect(存储.读取(首次).toString()).toBe('sample')
    存储.增加引用(首次)
    expect(存储.列表()).toMatchObject([{ 标识: 首次, 引用次数: 1 }])
  })

  it('超过大小限制与引用错误返回实际原因', () => {
    const 存储 = 创建资源存储({ 最大单项字节: 4, 最大总字节: 8 })
    expect(() => 存储.加入(Buffer.from('12345'), 'image/png')).toThrow(/单项/)
    const 标识 = 存储.加入(Buffer.from('1234'), 'image/png')
    expect(() => 存储.解除引用('不存在')).toThrow(/不存在/)
    存储.解除引用(标识)
    expect(() => 存储.解除引用(标识)).toThrow(/引用/)
  })

  it('恢复按真实单项与总字节限制校验，整批失败不留下部分资源', () => {
    const 来源 = 创建资源存储()
    const 标识列表 = ['1234', '5678', 'abcd', '12345'].map(内容 => 来源.加入(Buffer.from(内容), 'image/png'))
    const 备份 = 来源.导出(标识列表)
    const 存储 = 创建资源存储({ 最大单项字节: 4, 最大总字节: 8 })
    expect(() => 存储.恢复([备份[3]])).toThrow(/单项/)
    expect(() => 存储.恢复(备份.slice(0, 3))).toThrow(/总大小/)
    expect(存储.列表()).toEqual([])
    存储.恢复([备份[0], 备份[0], 备份[1]])
    expect(存储.列表()).toHaveLength(2)
  })
})
