const JSZip = require('jszip')
const { 写入pptx, 读取pptx } = require('../pptxCodec')
const { 写入讲义母版, 读取讲义母版, 写入备注母版页眉页脚, 读取备注母版页眉页脚, 校验母版设置 } = require('./handoutMasters')

const 基础包 = async () => JSZip.loadAsync(await 写入pptx({ 幻灯片: [{ id: '页', 背景色: '#FFFFFF', 备注: '备注内容', 文本框: [{ id: '文字', text: '正文', x: 0, y: 0, width: 100, height: 40, 字号: 18 }] }] }))
const 设置 = { 每页张数: 6, 页眉: '培训讲义', 页脚: '第 <页码> 页', 显示日期: true, 显示页码: true }

describe('讲义母版与备注母版页眉页脚', () => {
  it('写入讲义母版后包含部件、内容类型、关系与母版引用，并能读回设置', async () => {
    const 包 = await 基础包()
    const 结果 = await 写入讲义母版(包, 设置)
    expect(结果.成功).toBe(true)
    const 部件 = await 包.file('ppt/handoutMasters/handoutMaster1.xml').async('string')
    expect(部件).toContain('<p:hf')
    expect(部件).toMatch(/hdr="1"/)
    expect(部件).toMatch(/ftr="1"/)
    expect(部件).toMatch(/dt="1"/)
    expect(部件).toMatch(/sldNum="1"/)
    expect(部件).toContain('培训讲义')
    expect(await 包.file('[Content_Types].xml').async('string')).toContain('/ppt/handoutMasters/handoutMaster1.xml')
    expect(await 包.file('ppt/_rels/presentation.xml.rels').async('string')).toContain('handoutMaster')
    expect(await 包.file('ppt/presentation.xml').async('string')).toContain('handoutMasterIdLst')
    expect(await 读取讲义母版(包)).toEqual(设置)
  })

  it('重复写入只更新一份母版与一条关系', async () => {
    const 包 = await 基础包()
    await 写入讲义母版(包, 设置)
    await 写入讲义母版(包, { ...设置, 页眉: '第二次', 显示日期: false })
    const 关系 = await 包.file('ppt/_rels/presentation.xml.rels').async('string')
    expect(关系.match(/Type="[^"]*\/handoutMaster"/g)).toHaveLength(1)
    const 内容类型 = await 包.file('[Content_Types].xml').async('string')
    expect(内容类型.match(/handoutMaster1\.xml/g)).toHaveLength(1)
    const 演示 = await 包.file('ppt/presentation.xml').async('string')
    expect(演示.match(/<p:handoutMasterIdLst\b/g)).toHaveLength(1)
    const 读回 = await 读取讲义母版(包)
    expect(读回).toMatchObject({ 页眉: '第二次', 显示日期: false, 显示页码: true })
  })

  it('备注母版写入页眉页脚开关并保留既有占位符内容', async () => {
    const 包 = await 基础包()
    const 原内容 = await 包.file('ppt/notesMasters/notesMaster1.xml').async('string')
    expect(原内容).not.toContain('<p:hf')
    await 写入备注母版页眉页脚(包, { 排版: '幻灯片加备注', 页眉: '备注页眉', 页脚: '第 <页码> 页', 显示日期: false, 显示页码: true })
    const 部件 = await 包.file('ppt/notesMasters/notesMaster1.xml').async('string')
    expect(部件).toContain('<p:hf')
    expect(部件).toMatch(/hdr="1"/)
    expect(部件).toMatch(/ftr="1"/)
    expect(部件).toMatch(/dt="0"/)
    expect(部件).toMatch(/sldNum="1"/)
    expect(部件).toContain('备注页眉')
    expect(部件.length).toBeGreaterThan(原内容.length)
    expect(await 读取备注母版页眉页脚(包)).toMatchObject({ 页眉: '备注页眉', 显示日期: false, 显示页码: true })
    await 写入备注母版页眉页脚(包, { 排版: '仅备注', 页眉: '改后', 页脚: '', 显示日期: true, 显示页码: false })
    const 第二次 = await 包.file('ppt/notesMasters/notesMaster1.xml').async('string')
    expect(第二次.match(/<p:hf\b/g)).toHaveLength(1)
    expect(第二次).toContain('改后')
    expect(第二次).not.toContain('备注页眉')
  })

  it('读取没有母版设置的文件时返回空值，损坏部件报真实原因', async () => {
    const 包 = await 基础包()
    expect(await 读取讲义母版(包)).toBeNull()
    expect(await 读取备注母版页眉页脚(包)).toBeNull()
    包.file('ppt/handoutMasters/handoutMaster1.xml', '<p:handoutMaster>')
    await expect(读取讲义母版(包)).rejects.toThrow('讲义母版')
    包.file('ppt/notesMasters/notesMaster1.xml', '<p:notesMaster>')
    await expect(读取备注母版页眉页脚(包)).rejects.toThrow('备注母版')
  })

  it('设置非法或压缩包缺少必要部件时拒绝写入', async () => {
    expect(() => 校验母版设置({ ...设置, 每页张数: 5 })).toThrow('讲义每页张数')
    expect(() => 校验母版设置({ ...设置, 页脚: 'x'.repeat(200) })).toThrow('页脚')
    const 包 = new JSZip()
    await expect(写入讲义母版(包, 设置)).rejects.toThrow('压缩包')
  })

  it('母版设置随 PPTX 保存重开保留', async () => {
    const 包 = await 基础包()
    await 写入讲义母版(包, 设置)
    await 写入备注母版页眉页脚(包, { 排版: '幻灯片加备注', 页眉: '备注页眉', 页脚: '', 显示日期: true, 显示页码: true })
    const 字节 = await 包.generateAsync({ type: 'nodebuffer' })
    const 读取 = await 读取pptx(字节)
    expect(读取.警告).toEqual([])
    expect(读取.演示文稿.幻灯片列表[0].备注).toBe('备注内容')
    const 重开 = await JSZip.loadAsync(字节)
    expect(await 读取讲义母版(重开)).toEqual(设置)
    expect(await 读取备注母版页眉页脚(重开)).toMatchObject({ 页眉: '备注页眉', 显示日期: true })
  })
})
