import {useEffect,useRef,useState} from 'react'
import {App,Button,Checkbox,Input,Modal,Select,Switch,Tag} from 'antd'
import {cloudCall,useCloud} from './CloudProvider'
import {extractUpload,readUpload,retrieval,type Passage} from './fileData'
import {recognizeScans} from './scanConsent'
import {reportPublic} from './reportPublic'
const builtins=[
  {id:'seal-kb-1',name:'海豹办公 · 文件与备份',text:'海豹办公在本地打开文字、表格、演示与 PDF。手动保存会写入你选择的路径。云空间与云文档自动保存默认关闭，需要主动开通。云端保存失败时保留本地改动；云空间停用会关闭自动保存。文件内容关键词搜索可在首页查找。',location:'使用指南'},
  {id:'seal-kb-2',name:'海豹办公 · 云空间与隐私',text:'每账号云空间实际配额 300 MB，文件、版本和回收站占用配额。私有文件在客户端加密后上传，服务器不持有解密密钥。换设备或重新登录时需要恢复密钥。密钥与授权设备全部丢失后无法恢复。公开内容能够被其他用户和管理员阅读。在线 AI 处理资料需要单次同意。',location:'隐私说明'},
  {id:'seal-kb-3',name:'表格入门 · 数据整理',text:'表格中的一行通常代表一条记录，一列代表一种字段。使用统一的日期、金额和名称格式可以减少错误。合并单元格适合展示标题，明细数据尽量不合并。排序前选择完整区域，避免字段与记录错位。筛选会隐藏不满足条件的行，清除筛选后恢复显示。',location:'数据整理'},
  {id:'seal-kb-4',name:'演示入门 · 结构与表达',text:'汇报演示可以按目标、现状、证据、建议、行动安排五部分组织。每页表达一个主要观点。图表标明单位、时间范围和数据来源。正文使用短句，复杂资料放入备注或附录。放映前检查字体、图片与媒体，并准备 PDF 备份。',location:'演示编排'},
  {id:'seal-kb-5',name:'文字入门 · 排版与打印',text:'标题样式帮助组织文档结构。段落间距与行距应统一。使用分页符开始新页，避免用大量空行分页。打印前通过预览检查纸张、方向、页边距、图片和页眉页脚。导入有兼容性提示的文件先另存副本，保留原始文件。',location:'排版与打印'},
  {id:'seal-kb-6',name:'PDF 入门 · 文字与扫描件',text:'有文字层的 PDF 可以选择并复制文字。扫描件通常只有图片，需要 OCR 识别；识别结果需要核对。添加文字或覆盖区域并不等于安全删除原内容，涉及敏感信息时须使用真正的内容删除工具并验证提取结果。编辑完成后另存，并重新打开检查每页。',location:'PDF 基础'}
]
interface Knowledge {id:string;kind:string;parent:string|null;deleted:number;meta:{name:string;text?:string;cover?:string};updated:number}
export default function KnowledgePage(){
  const {state,configure,refresh}=useCloud(),{modal,message}=App.useApp(),[nodes,setNodes]=useState<Knowledge[]>([]),[publicItems,setPublicItems]=useState<any[]>([]),[myPublic,setMyPublic]=useState<any[]>([]),[scope,setScope]=useState('all'),[search,setSearch]=useState(''),[question,setQuestion]=useState(''),[selected,setSelected]=useState<{id:string;name:string;passages:Passage[];public?:boolean}|null>(null),[answer,setAnswer]=useState(''),[citations,setCitations]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[upload,setUpload]=useState<{file:File;data:string;passages:Passage[]}|null>(null),[name,setName]=useState(''),[cover,setCover]=useState(''),[publicOn,setPublicOn]=useState(false),[publicConsent,setPublicConsent]=useState(false),[library,setLibrary]=useState<string|null>(null)
  const context=useRef('');context.current=JSON.stringify([state.account?.id,state.account?.enabled,state.unlocked,search])
  const load=async()=>{const key=context.current;try{const publicResult=await cloudCall('public',{query:search});let privateNodes:Knowledge[]=[],publications:any[]=[];if(state.account?.enabled&&state.unlocked){privateNodes=await cloudCall('list');publications=(await cloudCall('myPublic')).items}if(key!==context.current)return;setPublicItems(publicResult.items);setNodes(privateNodes);setMyPublic(publications);setError('')}catch(e){if(key===context.current)setError(e instanceof Error?e.message:'读取失败')}}
  useEffect(()=>{setNodes([]);setMyPublic([]);setSelected(null);setAnswer('');setCitations([]);void load()},[state.account?.id,state.account?.enabled,state.unlocked])
  useEffect(()=>{const timer=setTimeout(()=>{void load()},300);return()=>clearTimeout(timer)},[search])
  const run=async(task:()=>Promise<any>)=>{setBusy(true);try{await task()}catch(e){modal.error({title:'知识库操作失败',content:e instanceof Error?e.message:'操作失败'})}finally{setBusy(false)}}
  const createLibrary=()=>{if(!state.account?.enabled||!state.unlocked){configure();return}let title='';modal.confirm({title:'新建知识库',content:<Input aria-label="知识库名称" onChange={e=>title=e.target.value}/>,onOk:()=>run(async()=>{if(!title.trim())throw new Error('请填写知识库名称');await cloudCall('folder',{name:title.trim(),kind:'library'});await load()})})}
  const items=nodes.filter(n=>n.kind==='knowledge'&&!n.deleted&&(scope==='all'||scope==='mine'||n.parent===scope)&&(n.meta.name+' '+(n.meta.text||'')).toLowerCase().includes(search.toLowerCase()))
  const [highlight,setHighlight]=useState('')
  const passageId=(id:string,location:string)=>'seal-source-'+encodeURIComponent(id+'-'+location)
  const jump=async(c:any)=>{
    if(c.id!==selected?.id){const b=builtins.find(b=>b.id===c.id),n=nodes.find(n=>n.id===c.id);if(b)setSelected({id:b.id,name:b.name,passages:[{location:b.location,text:b.text}]});else if(n)setSelected({id:n.id,name:n.meta.name,passages:JSON.parse(n.meta.text||'[]')});else{const r=await cloudCall('publicRead',{id:c.id});setSelected({id:c.id,name:r.title,passages:JSON.parse(r.text||'[]'),public:true})}}
    const target=passageId(c.id,c.location);setHighlight(target);setTimeout(()=>document.getElementById(target)?.scrollIntoView({block:'center',behavior:'smooth'}),0)
  }
  const selectPrivate=(n:Knowledge)=>{setSelected({id:n.id,name:n.meta.name,passages:JSON.parse(n.meta.text||'[]')});setAnswer('');setCitations([])}
  const ask=()=>void run(async()=>{const key=context.current;if(!question.trim())return;if(selected?.public)await cloudCall('publicRead',{id:selected.id});let sources=selected?selected.passages.map(p=>({...p,id:selected.id,name:selected.name})):scope==='all'?[...builtins.flatMap(b=>[{id:b.id,name:b.name,location:b.location,text:b.text}]),...items.flatMap(n=>{try{return JSON.parse(n.meta.text||'[]').map((p:Passage)=>({...p,id:n.id,name:n.meta.name}))}catch{return []}})]:items.flatMap(n=>{try{return JSON.parse(n.meta.text||'[]').map((p:Passage)=>({...p,id:n.id,name:n.meta.name}))}catch{return []}});if(!selected&&['all','public'].includes(scope)){if(scope==='public')sources=[];for(const item of publicItems.filter(p=>p.kind==='knowledge').slice(0,8)){try{const r=await cloudCall('publicRead',{id:item.id});sources.push(...JSON.parse(r.text||'[]').map((p:Passage)=>({...p,id:item.id,name:item.title})))}catch{}}}if(key!==context.current)return;sources=retrieval(sources,question).map(s=>s as any);if(!sources.some(s=>s.text.trim())){message.warning('请先选择包含文字的知识文件，扫描件需要识别');return}modal.confirm({title:'本次在线 AI 资料授权',content:<><p>将把以下选定资料片段发送给当前配置的 AI 服务。本次处理期间该服务可读取这些片段。</p><div className="seal-knowledge-source">{sources.map(s=>`${s.name} · ${s.location}\n${s.text}`).join('\n\n')}</div></>,okText:'同意并提问',cancelText:'取消',onOk:()=>run(async()=>{if(key!==context.current)throw new Error('账号或资料范围已变动，请重新提问');for(const id of [...new Set(sources.filter(s=>publicItems.some(p=>p.id===s.id)).map(s=>s.id))])await cloudCall('publicRead',{id});const r=await cloudCall('question',{question,sources,consent:true});if(key!==context.current)return;if(!r.answer.trim())throw new Error('AI 返回内容为空，请重试');setAnswer(r.answer);setCitations(r.sources)})})})
  return <section className="seal-cloud-page"><header><h1>海豹知识库</h1><div><Button onClick={createLibrary}>新建知识库</Button> <Button loading={busy} onClick={()=>void load()}>刷新</Button></div></header>
    <div className="seal-cloud-form"><Input.TextArea aria-label="知识库问题" placeholder="向选定资料提问，回答附来源" rows={2} value={question} onChange={e=>setQuestion(e.target.value)}/><Button type="primary" loading={busy} onClick={ask}>提问</Button></div>
    {error?<p className="seal-cloud-error">{error}</p>:null}
    <div className="seal-cloud-actions"><Select value={scope} style={{minWidth:170}} onChange={v=>{setScope(v);setSelected(null);setAnswer('');setCitations([])}} options={[{value:'all',label:'全部知识'},{value:'mine',label:'我的知识文件'},{value:'public',label:'公开知识广场'},...nodes.filter(n=>n.kind==='library'&&!n.deleted).map(n=>({value:n.id,label:n.meta.name}))]}/><Input.Search aria-label="搜索知识库" placeholder="搜索知识名称" value={search} onChange={e=>setSearch(e.target.value)} style={{maxWidth:260}}/><label className="ant-btn"><input type="file" hidden accept=".docx,.xlsx,.pptx,.pdf,.txt,.md" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!state.account?.enabled||!state.unlocked){configure();return}void run(async()=>{const data=await readUpload(file,10*1024*1024),passages=await extractUpload(file.name,data,images=>recognizeScans(modal,images));setUpload({file,data,passages});setName(file.name);setCover('');setPublicOn(false);setPublicConsent(false);setLibrary(null)})}}/>上传知识文件</label></div>
    {selected?<div className="seal-knowledge-workspace"><div><h2>{selected.name}</h2><Button onClick={()=>setSelected(null)}>返回知识列表</Button>{!selected.id.startsWith('seal-kb')?<Button onClick={()=>void run(async()=>{await cloudCall('download',{id:selected.id,public:selected.public,name:selected.name})})}>下载原文件</Button>:null}<div className="seal-knowledge-source">{selected.passages.map((p,i)=><section key={i} id={passageId(selected.id,p.location)} style={{background:highlight===passageId(selected.id,p.location)?'var(--bg-hover,#dfeaff)':undefined}}><h3>{p.location}</h3><p>{p.text}</p></section>)}</div></div><div><h2>知识问答</h2><div className="seal-knowledge-answer">{answer||'输入问题，确认资料授权后开始对话。'}</div>{citations.map((c,i)=><Button key={i} onClick={()=>void run(()=>jump(c))}>{c.name} · {c.location}</Button>)}{answer&&!citations.length?<p>本次回答没有可跳转的有效引用，请对照资料核验。</p>:null}</div></div>:<>
      {answer?<div className="seal-knowledge-answer">{answer}{citations.map((c,i)=><Button key={i} onClick={()=>void run(()=>jump(c))}>{c.name} · {c.location}</Button>)}</div>:null}
      <div className="seal-cloud-list">{scope==='all'?builtins.filter(b=>(b.name+' '+b.text).toLowerCase().includes(search.toLowerCase())).map(b=><article className="seal-cloud-card" key={b.id}><Tag>内置 · 原创指南</Tag><h3>{b.name}</h3><p>{b.text.slice(0,100)}…</p><Button onClick={()=>{setSelected({id:b.id,name:b.name,passages:[{location:b.location,text:b.text}]});setAnswer('')}}>阅读与提问</Button></article>):null}
      {scope!=='public'?items.map(n=>{const pub=myPublic.find(p=>p.node_id===n.id&&!['withdrawn','rejected'].includes(p.status));return <article className="seal-cloud-card" key={n.id}>{n.meta.cover?<img src={n.meta.cover} alt="知识封面"/>:<Tag>私有 · 加密</Tag>}<h3>{n.meta.name}</h3><Button onClick={()=>selectPrivate(n)}>阅读与提问</Button><Button onClick={()=>void run(()=>cloudCall('download',{id:n.id}))}>下载</Button><Switch checked={Boolean(pub)} checkedChildren="公开" unCheckedChildren="私有" onChange={on=>on?modal.confirm({title:'发布到公开知识广场？',content:'其他用户和管理员可查看、下载和引用公开副本。关闭后已下载副本无法收回。',onOk:()=>run(async()=>{await cloudCall('publish',{id:n.id,kind:'knowledge',consent:true});await load()})}):void run(async()=>{await cloudCall('withdraw',{id:pub.id});await load()})}/>{pub?<p>{pub.status==='pending'?'审核中':'已公开'}</p>:null}</article>}):null}
      {['all','public'].includes(scope)?publicItems.filter(p=>p.kind==='knowledge').map(p=><article className="seal-cloud-card" key={p.id}>{p.cover?<img src={p.cover} alt="公开知识封面"/>:<Tag>公开知识</Tag>}<h3>{p.title}</h3><Button onClick={()=>void run(async()=>{const r=await cloudCall('publicRead',{id:p.id});let passages:Passage[];try{passages=JSON.parse(r.text)}catch{passages=[{location:'正文',text:r.text}]}setSelected({id:p.id,name:p.title,passages,public:true});setAnswer('')})}>浏览与一键引用</Button><Button onClick={()=>void run(()=>cloudCall('download',{id:p.id,public:true,name:p.title}))}>下载</Button><Button onClick={()=>state.account?reportPublic(modal,message,p.id):configure()}>举报</Button></article>):null}</div>
    </>}
    <Modal title="上传知识文件" open={Boolean(upload)} centered confirmLoading={busy} onCancel={()=>setUpload(null)} okText="加密上传" okButtonProps={{disabled:!name.trim()||(publicOn&&!publicConsent)}} onOk={()=>run(async()=>{if(!upload)return;const r=await cloudCall('save',{linkId:crypto.randomUUID(),name:name.trim(),filename:upload.file.name,data:upload.data,kind:'knowledge',parent:library,text:JSON.stringify(upload.passages),cover});setUpload(null);if(r.statuses[r.id]!=='云端已保存'){message.info('文件已在本机加密保留，请到云空间重试同步；同步完成后再申请公开');await refresh();return}if(publicOn)await cloudCall('publish',{id:r.id,kind:'knowledge',consent:publicConsent});setUpload(null);await load();await refresh();message.success('知识文件已上传')})}>
      <Input aria-label="知识文件名称" placeholder="自定义名称" value={name} onChange={e=>setName(e.target.value)}/><p>原文件：{upload?.file.name}，最多 10 MiB。</p><Select style={{width:'100%'}} placeholder="选择知识库（可选）" allowClear value={library||undefined} onChange={v=>setLibrary(v||null)} options={nodes.filter(n=>n.kind==='library'&&!n.deleted).map(n=>({value:n.id,label:n.meta.name}))}/><p><label>自定义封面 <input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{if(f.size>700000)throw new Error('封面最多 700 KB');setCover(`data:${f.type};base64,${await readUpload(f)}`)})}}/></label></p><Switch aria-label="上传后公开" checked={publicOn} onChange={setPublicOn}/> 上传后申请公开{publicOn?<p><Checkbox checked={publicConsent} onChange={e=>setPublicConsent(e.target.checked)}>我确认公开副本可被其他用户及管理员查看、下载和引用</Checkbox></p>:null}
    </Modal>
  </section>
}
