const office = require('../../main/ipc/officeChannel')
const ai = require('../../main/ipc/aiChannel')
const presentationAi = require('../../main/ipc/presentationAiChannel')
const generation = require('../../main/ipc/presentationGenerationChannel')
const cloud = require('../../main/ipc/cloudChannel')
const presentation = require('../../main/ipc/presentationChannel')
const assistant = require('../../main/ai/assistant')
const services = require('../../main/ai/services')
const cloudService = require('../../main/cloud/service')
const pdf = require('../../main/pdf/pdfTools')
const recognition = require('../../main/ppt/recognition')
const recording = require('../../main/ppt/recording')
const platform = require('./shims/electron.js')
const storage = require('./shims/fs.js')
const vault = require('./shims/vault.js')
const crypto = require('./shims/crypto.js')
require('../../main/preload.js')
module.exports = { office, ai, presentationAi, generation, cloud, presentation, assistant, services, cloudService, pdf, recognition, recording, platform, storage, vault, crypto }
